version: '3'

services:
  server:
    ports:
      - "3333:3333"
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - start:server
    env_file:
      - .env.dist
    volumes:
      - ./:/usr/src/app
    environment:
      NODE_ENV: development
    networks:
      - nesty-network
    restart: always
    depends_on:
      - mongo
  client:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - start:client
    env_file:
      - .env.dist
    volumes:
      - ./:/usr/src/app
    environment:
      NODE_ENV: development
    networks:
      - nesty-network
    restart: always
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:3.6
    restart: always
    ports:
      - "27017:27017"
    networks:
      - nesty-network
networks:
  nesty-network:
    driver: bridge
